language: node_js
node_js:
  - "stable" 
script:
    - 'echo "Hello! This is Travis"'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token_ayush.me
  keep_history: true
  on:
    branch: master